using Newtonsoft.Json;

namespace CampaignDistribution.CampaignDistributionDL.Campaign.Model
{
    /// <summary>
    /// Specifies the code generation method for the vouchers in a campaign
    /// </summary>
    
    [JsonObject]
    public class VoucherCodeConfig
    {
        /// <summary>
        /// The pattern of a voucher code
        /// <para><ex>JJ###KT  </ex></para>
        /// <para>JJ is the prefix.  </para>
        /// <para>KT is the suffix.   </para>
        /// <para>'###' is the variable or random part   </para>
        /// <para>Length of code = prefix + variable part + suffix   </para>
        /// <para>Only necessary if autogenerate is false</para>
        /// </summary>
        /// <value></value>
        [JsonProperty(PropertyName="pattern")]
        public string Pattern { get; set; }

        /// <summary>
        /// If true voucher code will be autogenerated
        /// Else user will need to specify pattern
        /// </summary>
        /// <value></value>
        
        [JsonProperty(PropertyName="autogenerate")]
        public bool Autogenerate { get; set; }
    }
}